# utils/exporter.py
# ============================================================
# Export System — Phase 10
# Exports generated questions to TXT, DOCX, and CSV formats.
# ============================================================

import os
import csv
from docx import Document
from docx.shared import Pt, RGBColor
from generators.formatter import get_question_objects

# Make sure exports folder exists
os.makedirs("exports", exist_ok=True)


# ============================================================
# EXPORT 1: TXT
# ============================================================

def export_to_txt(formatted_text):
    """
    Saves formatted question text to a .txt file.

    Args:
        formatted_text : string from format_questions_for_display()

    Returns:
        File path string or None if failed.
    """

    if not formatted_text or formatted_text.strip() == "":
        return None

    path = "exports/questions.txt"

    with open(path, "w", encoding="utf-8") as f:
        f.write(formatted_text)

    print(f"TXT exported: {path}")
    return path


# ============================================================
# EXPORT 2: CSV
# ============================================================

def export_to_csv(formatted_text, context):
    """
    Saves questions as a structured CSV file.
    One row per question with all fields as columns.

    Args:
        formatted_text : string from format_questions_for_display()
        context        : context dict for metadata

    Returns:
        File path string or None if failed.
    """

    if not formatted_text or not context:
        return None

    # Parse questions into objects
    questions = get_question_objects(formatted_text, context)

    if not questions:
        return None

    path = "exports/questions.csv"

    # CSV column headers
    fieldnames = [
        "question_number",
        "topic",
        "difficulty",
        "question",
        "expected_output",
        "solution_query",
    ]

    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for q in questions:
            writer.writerow(q.to_csv_row())

    print(f"CSV exported: {path} — {len(questions)} questions")
    return path


# ============================================================
# EXPORT 3: DOCX
# ============================================================

def export_to_docx(formatted_text, context):
    """
    Saves questions as a formatted .docx file.
    Opens and edits perfectly in Google Docs.

    Args:
        formatted_text : string from format_questions_for_display()
        context        : context dict for metadata

    Returns:
        File path string or None if failed.
    """

    if not formatted_text or not context:
        return None

    # Parse questions into objects
    questions = get_question_objects(formatted_text, context)

    path = "exports/questions.docx"
    doc  = Document()

    # ── Document title ───────────────────────────────────────
    title      = doc.add_heading("SQL Question Bank", level=0)
    title_run  = title.runs[0]
    title_run.font.color.rgb = RGBColor(0x1F, 0x35, 0x64)

    # Subtitle with metadata
    subtitle = doc.add_paragraph()
    subtitle.add_run(
        f"Topic: {context.get('topic', '')}  |  "
        f"Difficulty: {context.get('difficulty', '')}  |  "
        f"Table: {context.get('table_name', '')}"
    ).font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    doc.add_paragraph("Generated by SQL Question Bank Generator — PostgreSQL")
    doc.add_paragraph("─" * 55)

    # ── Add each question ────────────────────────────────────
    if questions:
        for q in questions:
            # Question heading
            heading = doc.add_heading(
                f"Question {q.number}  —  {q.topic}  |  {q.difficulty}",
                level=2
            )
            heading.runs[0].font.color.rgb = RGBColor(0x1F, 0x35, 0x64)

            # Question text label
            p = doc.add_paragraph()
            run = p.add_run("Question:")
            run.bold = True
            run.font.color.rgb = RGBColor(0x2E, 0x4A, 0x6B)

            # Question text content
            doc.add_paragraph(q.question_text.strip())

            # Expected output label
            p = doc.add_paragraph()
            run = p.add_run("Expected Output Columns:")
            run.bold = True
            run.font.color.rgb = RGBColor(0x2E, 0x4A, 0x6B)

            # Expected output content
            doc.add_paragraph(q.expected_output.strip())

            # Solution label
            p = doc.add_paragraph()
            run = p.add_run("PostgreSQL Solution:")
            run.bold = True
            run.font.color.rgb = RGBColor(0x2E, 0x4A, 0x6B)

            # SQL query in monospace green
            sql_para = doc.add_paragraph(style="No Spacing")
            sql_run  = sql_para.add_run(q.solution_query.strip())
            sql_run.font.name  = "Courier New"
            sql_run.font.size  = Pt(10)
            sql_run.font.color.rgb = RGBColor(0x1A, 0x5C, 0x2A)

            # Separator between questions
            doc.add_paragraph("─" * 55)

    else:
        # Fallback — write raw text if parsing failed
        doc.add_paragraph(formatted_text)

    doc.save(path)
    print(f"DOCX exported: {path}")
    return path